(function treasuryFeature(global) {
  "use strict";

  const root = document.getElementById("treasury");
  if (!root) return;

  const store = { contracts: [], installments: [], movements: [], events: [], audit: [], evidence: [], overdueAlerts: [], capabilities: {}, loaded: false, selectedId: "", filters: { query: "", status: "all" }, pagination: { movements: 1, audit: 1, pageSize: 10 } };
  const dateLabel = new Intl.DateTimeFormat("es-PE", { day: "2-digit", month: "short", year: "numeric" });
  const dateTimeLabel = new Intl.DateTimeFormat("es-PE", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
  const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));
  const amount = (value) => Number(value || 0);
  const byId = (id) => document.getElementById(id);
  const service = () => global.OneStudios?.services?.treasury;
  const todayIso = () => new Date().toISOString().slice(0, 10);
  const parseDate = (value) => value ? new Date(`${String(value).slice(0, 10)}T12:00:00`) : null;
  const formatDate = (value) => { const parsed = parseDate(value); return parsed ? dateLabel.format(parsed) : "—"; };
  const formatDateTime = (value) => { const parsed = value ? new Date(value) : null; return parsed && !Number.isNaN(parsed.getTime()) ? dateTimeLabel.format(parsed) : "—"; };
  const formatMoney = (value, currency = "PEN") => new Intl.NumberFormat("es-PE", { style: "currency", currency: currency || "PEN" }).format(amount(value));
  const capability = (name) => store.capabilities?.[name] === true;

  function shell() {
    root.innerHTML = `<div class="tr-shell">
      <header class="tr-hero"><div><span class="tr-eyebrow">Control financiero</span><h2>Tesorería y contratos</h2><p>Seguimiento de contratos, cuotas, cobranzas, gastos y capital disponible con estados auditables.</p></div><div class="tr-actions"><button class="tr-secondary" id="trRefresh" type="button">Actualizar</button><button class="tr-secondary" id="trNewMovement" type="button">Registrar movimiento</button><button class="tr-primary" id="trNewContract" type="button">+ Nuevo contrato</button></div></header>
      <div class="tr-kpis" id="trKpis"></div>
      <div class="tr-toolbar"><div class="tr-tabs" role="tablist"><button class="active" data-tr-tab="overview">Resumen</button><button data-tr-tab="contracts">Contratos</button><button data-tr-tab="movements">Movimientos</button><button data-tr-tab="audit" id="trAuditTab">Auditoría</button></div><span class="tr-status" id="trStatus">Esperando sesión segura…</span></div>
      <section class="tr-panel active" data-tr-panel="overview"><div class="tr-overdue-wrap" id="trOverdueAlerts"></div><div class="tr-grid"><article class="tr-card"><div class="tr-card-head"><div><span class="tr-eyebrow">Flujo mensual</span><h3>Real y proyectado</h3></div><div class="tr-legend"><span><i style="--legend:#7357ff"></i>Ingresos</span><span><i style="--legend:#ef8a9a"></i>Gastos</span><span><i style="--legend:#9ea5b6"></i>Proyección</span></div></div><div class="tr-chart" id="trChart"></div></article></div></section>
      <section class="tr-panel" data-tr-panel="contracts"><div class="tr-contract-tools"><label><span>Buscar contrato</span><input id="trContractSearch" placeholder="Número, cliente, documento o servicio"></label><label><span>Estado</span><select id="trContractStatus"><option value="all">Todos</option><option value="draft">Borradores</option><option value="active">Activos</option><option value="completed">Completados</option><option value="cancelled">Anulados</option><option value="overdue">Con cuotas vencidas</option></select></label><button type="button" id="trExportContracts">Exportar CSV</button></div><div class="tr-table-wrap"><table><thead><tr><th>Contrato</th><th>Cliente</th><th>Servicio</th><th>Total</th><th>Cobrado</th><th>Saldo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody id="trContractsBody"></tbody></table></div></section>
      <section class="tr-panel" data-tr-panel="movements"><div class="tr-table-wrap"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Categoría / detalle</th><th>Contrato</th><th>Método</th><th>Registrado por</th><th>Evidencia</th><th class="tr-amount">Monto</th><th>Acciones</th></tr></thead><tbody id="trMovementsBody"></tbody></table></div><div class="tr-pagination" id="trMovementsPagination"></div></section>
      <section class="tr-panel" data-tr-panel="audit"><div class="tr-card"><div class="tr-card-head"><div><span class="tr-eyebrow">Trazabilidad financiera</span><h3>Quién realizó cada cambio</h3></div></div><div class="tr-table-wrap"><table><thead><tr><th>Fecha y hora</th><th>Acción</th><th>Entidad</th><th>Registro</th><th>Realizado por</th><th>Detalle</th></tr></thead><tbody id="trAuditBody"></tbody></table></div><div class="tr-pagination" id="trAuditPagination"></div></div></section>

      <dialog id="trContractDialog"><div class="tr-dialog-head"><div><h3 id="trContractDialogTitle">Registrar contrato</h3><p>La información alimentará cuotas, cobranzas e impresión.</p></div><button class="tr-close" data-tr-close="trContractDialog" type="button">×</button></div><form id="trContractForm"><input id="trContractId" type="hidden"><div class="tr-form-grid">
        <div class="tr-document-row"><span class="tr-document-label">Documento <i class="tr-required" aria-hidden="true">*</i></span><select id="trDocumentType" aria-label="Tipo de documento"><option value="DNI">DNI</option><option value="RUC">RUC</option><option value="CE">CE</option></select><input id="trDocument" inputmode="numeric" aria-label="Número de documento, obligatorio" placeholder="Número de documento" required><button id="trLookup" type="button">Consultar</button></div><div class="tr-api-note" id="trApiNote">Puedes consultar DNI o RUC y verificar el resultado antes de guardar.</div>
        <label class="tr-span-2"><span>Nombre o razón social <i class="tr-required" aria-hidden="true">*</i></span><input id="trClientName" maxlength="180" required></label><label>Dirección<input id="trClientAddress" maxlength="240"></label><label>Teléfono<input id="trClientPhone" maxlength="30"></label><label>Correo<input id="trClientEmail" type="email" maxlength="160"></label><label><span>Fecha del servicio <i class="tr-required" aria-hidden="true">*</i></span><input id="trServiceDate" type="date" required></label>
        <label class="tr-span-2"><span>Servicio o paquete <i class="tr-required" aria-hidden="true">*</i></span><input id="trServiceName" maxlength="180" placeholder="Ej. Sesión fotográfica Romance" required></label><label class="tr-span-2">Objeto del contrato<textarea id="trServiceDescription" placeholder="Describe el servicio profesional contratado"></textarea></label><label class="tr-span-2">Entregables (uno por línea)<textarea id="trDeliverables" placeholder="35 fotografías editadas&#10;2 videos tipo Reel"></textarea></label>
        <label><span>Monto total <i class="tr-required" aria-hidden="true">*</i></span><input id="trTotal" type="number" min="0.01" step="0.01" required></label><label id="trFirstPercentLabel"><span>Primer abono (%) <i class="tr-required" aria-hidden="true">*</i></span><input id="trFirstPercent" type="number" min="1" max="99" value="50" required></label><label><span>Plazo de entrega (días) <i class="tr-required" aria-hidden="true">*</i></span><input id="trDeliveryDays" type="number" min="1" max="365" value="7" required></label><label>Moneda<select id="trCurrency"><option value="PEN">Soles (PEN)</option><option value="USD">Dólares (USD)</option></select></label><label class="tr-span-2">Notas internas<textarea id="trContractNotes"></textarea></label><label class="tr-span-2" id="trChangeNoteLabel" hidden>Motivo del cambio<input id="trChangeNote" maxlength="200" placeholder="Ej. Corrección solicitada por el cliente"></label>
      </div><div class="tr-form-actions"><button data-tr-close="trContractDialog" type="button">Cancelar</button><button class="tr-primary" type="submit">Guardar contrato</button></div></form></dialog>

      <dialog id="trMovementDialog"><div class="tr-dialog-head"><div><h3 id="trMovementDialogTitle">Registrar movimiento</h3><p>Ingresos, gastos y aportes que actualizan la bóveda.</p></div><button class="tr-close" data-tr-close="trMovementDialog" type="button">×</button></div><form id="trMovementForm"><input id="trMovementId" type="hidden"><div class="tr-form-grid">
        <label>Tipo<select id="trMovementType"><option value="income">Ingreso / cobranza</option><option value="expense">Gasto</option><option value="contribution">Aporte de capital</option><option value="withdrawal">Retiro</option></select></label><label>Fecha<input id="trMovementDate" type="date" required></label><label class="tr-span-2">Contrato relacionado<select id="trMovementContract"><option value="">Sin contrato</option></select></label><label class="tr-span-2">Cuota relacionada<select id="trMovementInstallment"><option value="">Sin cuota específica</option></select></label><label>Categoría<input id="trMovementCategory" value="Cobranza" maxlength="80" required></label><label>Monto<input id="trMovementAmount" type="number" min="0.01" step="0.01" required></label><label>Método<select id="trPaymentMethod"><option value="transfer">Transferencia</option><option value="cash">Efectivo</option><option value="yape">Yape</option><option value="plin">Plin</option><option value="card">Tarjeta</option></select></label><label>Referencia<input id="trMovementReference" maxlength="100"></label><label class="tr-span-2">Descripción<textarea id="trMovementDescription"></textarea></label><label class="tr-span-2"><span>Evidencia fotográfica</span><input id="trMovementEvidence" type="file" accept="image/jpeg,image/png,image/webp" multiple><small class="tr-field-help">Hasta 5 imágenes JPG, PNG o WebP; máximo 10 MB cada una.</small><span class="tr-evidence-selection" id="trMovementEvidenceList"></span></label><label class="tr-span-2" id="trMovementReasonLabel" hidden><span>Motivo de la modificación <i class="tr-required" aria-hidden="true">*</i></span><input id="trMovementReason" maxlength="240" minlength="5" placeholder="Ej. Corrección del monto según comprobante"></label>
      </div><div class="tr-form-actions"><button data-tr-close="trMovementDialog" type="button">Cancelar</button><button class="tr-primary" id="trMovementSubmit" type="submit">Registrar movimiento</button></div></form></dialog>

      <dialog id="trDetailDialog" class="tr-detail-dialog"><div class="tr-dialog-head"><div><h3>Control del contrato</h3><p id="trDetailSubtitle"></p></div><button class="tr-close" data-tr-close="trDetailDialog" type="button">×</button></div><div class="tr-detail-body" id="trDetailBody"></div></dialog>
      <dialog id="trEvidenceDialog"><div class="tr-dialog-head"><div><h3>Evidencias del movimiento</h3><p>Archivos privados; el enlace de consulta vence en 15 minutos.</p></div><button class="tr-close" data-tr-close="trEvidenceDialog" type="button">×</button></div><div class="tr-evidence-body" id="trEvidenceBody"></div></dialog>
    </div>`;
    let print = byId("treasury-print");
    if (!print) { print = document.createElement("section"); print.id = "treasury-print"; document.body.appendChild(print); }
  }

  function movementSign(row) { return ["expense", "withdrawal"].includes(row.movement_type) ? -1 : 1; }
  function contractIncome(id) { return store.movements.filter((row) => row.movement_type === "income" && row.contract_id === id).reduce((sum, row) => sum + amount(row.amount), 0); }
  function installmentPaid(id) { return store.movements.filter((row) => row.movement_type === "income" && row.installment_id === id).reduce((sum, row) => sum + amount(row.amount), 0); }
  function installmentsFor(id) { return store.installments.filter((row) => row.contract_id === id); }
  function evidenceFor(id) { return store.evidence.filter((row) => row.movement_id === id); }
  function overdueInstallments(id) { const today = todayIso(); return installmentsFor(id).filter((row) => row.due_date < today && amount(row.amount) - installmentPaid(row.id) > .009); }
  function monthKey(value) { return String(value || "").slice(0, 7); }

  function metrics() {
    const currentMonth = todayIso().slice(0, 7);
    const monthRows = store.movements.filter((row) => monthKey(row.movement_date) === currentMonth);
    const income = monthRows.filter((row) => row.movement_type === "income").reduce((sum, row) => sum + amount(row.amount), 0);
    const expense = monthRows.filter((row) => row.movement_type === "expense").reduce((sum, row) => sum + amount(row.amount), 0);
    const vault = store.movements.reduce((sum, row) => sum + movementSign(row) * amount(row.amount), 0);
    const receivable = store.contracts.filter((row) => !["cancelled", "draft"].includes(row.status)).reduce((sum, row) => sum + Math.max(0, amount(row.total_amount) - contractIncome(row.id)), 0);
    const active = store.contracts.filter((row) => row.status === "active").length;
    const overdue = store.contracts.filter((row) => overdueInstallments(row.id).length).length;
    return { vault, income, expense, profit: income - expense, receivable, active, overdue };
  }

  function renderKpis() {
    const m = metrics();
    byId("trKpis").innerHTML = [["Bóveda",formatMoney(m.vault),"Capital disponible",m.vault>=0?"good":"warn"],["Ingresos del mes",formatMoney(m.income),"Cobranzas registradas","good"],["Gastos del mes",formatMoney(m.expense),"Egresos operativos",m.expense?"warn":""],["Ganancia del mes",formatMoney(m.profit),"Ingresos menos gastos",m.profit>=0?"good":"warn"],["Con atraso",m.overdue,"Contratos con cuotas vencidas",m.overdue?"bad":"good"]].map(([label,value,note,tone])=>`<article class="tr-kpi" data-tone="${tone}"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`).join("");
  }

  function monthSeries() {
    const result = [], now = new Date();
    for (let offset=-3; offset<=2; offset+=1) { const point=new Date(now.getFullYear(),now.getMonth()+offset,1),key=point.toISOString().slice(0,7),rows=store.movements.filter((row)=>monthKey(row.movement_date)===key),projected=store.installments.filter((row)=>monthKey(row.due_date)===key).reduce((sum,row)=>sum+Math.max(0,amount(row.amount)-installmentPaid(row.id)),0); result.push({label:point.toLocaleDateString("es-PE",{month:"short"}).replace(".",""),income:rows.filter((r)=>r.movement_type==="income").reduce((s,r)=>s+amount(r.amount),0),expense:rows.filter((r)=>r.movement_type==="expense").reduce((s,r)=>s+amount(r.amount),0),projected}); }
    return result;
  }

  function renderChart() {
    const series=monthSeries(),max=Math.max(1,...series.flatMap((row)=>[row.income,row.expense,row.projected])),width=720,base=205,group=width/series.length;
    const bars=series.map((row,index)=>{const x=index*group+25,ih=row.income/max*155,eh=row.expense/max*155,ph=row.projected/max*155;return `<rect x="${x}" y="${base-ih}" width="22" height="${ih}" rx="6" fill="#7357ff"/><rect x="${x+27}" y="${base-eh}" width="22" height="${eh}" rx="6" fill="#ef8a9a"/><rect x="${x+54}" y="${base-ph}" width="22" height="${ph}" rx="6" fill="#c8ccd7"/><text x="${x+38}" y="230" text-anchor="middle" fill="#737b8e" font-size="11">${esc(row.label)}</text>`;}).join("");
    byId("trChart").innerHTML=`<svg viewBox="0 0 ${width} 240" role="img" aria-label="Ingresos, gastos y cobros proyectados por mes"><line x1="12" y1="${base}" x2="708" y2="${base}" stroke="#e5e8ef"/>${bars}</svg>`;
  }

  function renderOverdueAlerts() {
    const host=byId("trOverdueAlerts"); if(!host)return;
    const rows=store.overdueAlerts||[];
    if(!rows.length){host.innerHTML="";host.hidden=true;return;}
    host.hidden=false;
    host.innerHTML=`<div class="tr-overdue-head"><div><span class="tr-eyebrow">Cobranza vencida</span><h3>${rows.length} cuota${rows.length===1?"":"s"} requiere${rows.length===1?"":"n"} atención</h3></div><span class="tr-badge bad">Alerta activa</span></div><div class="tr-overdue-list">${rows.map((item)=>`<button type="button" class="tr-overdue-row" data-tr-detail="${esc(item.contract_id)}"><div><strong>${esc(item.client_name||"Cliente")}</strong><small>${esc(item.contract_number||"")} · Cuota ${esc(item.installment_number)} · venció hace ${Number(item.days_overdue||0)} día${Number(item.days_overdue||0)===1?"":"s"}</small></div><div><strong>${formatMoney(item.pending_amount,item.currency)}</strong><small>Registró: ${esc(item.registered_by_name||"Sistema")} · Último cambio: ${esc(item.last_changed_by_name||"Sistema")}</small></div></button>`).join("")}</div>`;
  }

  function contractStatus(row) {
    if(row.status==="cancelled")return ["Anulado","bad"];
    if(overdueInstallments(row.id).length)return ["Vencido","bad"];
    if(row.status==="completed")return ["Completado","good"];
    if(row.status==="draft")return ["Borrador",""];
    const paid=contractIncome(row.id),total=amount(row.total_amount);
    if(paid>=total)return ["Pagado","good"];
    if(paid>0)return ["Pago parcial","warn"];
    return ["Activo",""];
  }

  function filteredContracts() {
    const query=store.filters.query.trim().toLocaleLowerCase("es");
    return store.contracts.filter((row)=>{
      if(store.filters.status==="overdue"&&!overdueInstallments(row.id).length)return false;
      if(!["all","overdue"].includes(store.filters.status)&&row.status!==store.filters.status)return false;
      return !query||[row.contract_number,row.client_name,row.client_document,row.service_name].some((value)=>String(value||"").toLocaleLowerCase("es").includes(query));
    });
  }

  function renderContracts() {
    const rows=filteredContracts();
    byId("trContractsBody").innerHTML=rows.length?rows.map((row)=>{const paid=contractIncome(row.id),status=contractStatus(row);return `<tr><td><strong>${esc(row.contract_number)}</strong><small>${formatDate(row.created_at)}</small></td><td><strong>${esc(row.client_name)}</strong><small>${esc(row.client_document_type)} ${esc(row.client_document)}</small></td><td><strong>${esc(row.service_name)}</strong><small>${formatDate(row.service_date)}</small></td><td>${formatMoney(row.total_amount,row.currency)}</td><td>${formatMoney(paid,row.currency)}</td><td>${formatMoney(Math.max(0,amount(row.total_amount)-paid),row.currency)}</td><td><span class="tr-badge ${status[1]}">${status[0]}</span></td><td><div class="tr-row-actions"><button type="button" data-tr-detail="${esc(row.id)}">Controlar</button>${capability("export")?`<button type="button" data-tr-print="${esc(row.id)}">Imprimir</button>`:""}</div></td></tr>`;}).join(""):`<tr><td colspan="8"><div class="tr-empty">No hay contratos que coincidan con los filtros.</div></td></tr>`;
  }

  function pageRows(rows,key) {
    const pages=Math.max(1,Math.ceil(rows.length/store.pagination.pageSize));
    store.pagination[key]=Math.min(Math.max(1,store.pagination[key]||1),pages);
    const start=(store.pagination[key]-1)*store.pagination.pageSize;
    return {rows:rows.slice(start,start+store.pagination.pageSize),page:store.pagination[key],pages,start};
  }

  function renderPagination(key,total,hostId) {
    const host=byId(hostId);if(!host)return;
    const pages=Math.max(1,Math.ceil(total/store.pagination.pageSize)),page=store.pagination[key],start=total?(page-1)*store.pagination.pageSize+1:0,end=Math.min(page*store.pagination.pageSize,total);
    host.innerHTML=`<span>Mostrando ${start}–${end} de ${total}</span><div><button type="button" data-tr-page-target="${key}" data-tr-page-delta="-1" ${page<=1?"disabled":""}>Anterior</button><strong>Página ${page} de ${pages}</strong><button type="button" data-tr-page-target="${key}" data-tr-page-delta="1" ${page>=pages?"disabled":""}>Siguiente</button></div>`;
  }

  function renderMovements() {
    const labels={income:"Ingreso",expense:"Gasto",contribution:"Aporte",withdrawal:"Retiro"};
    const page=pageRows(store.movements,"movements");
    byId("trMovementsBody").innerHTML=store.movements.length?page.rows.map((row)=>{const contract=store.contracts.find((item)=>item.id===row.contract_id),negative=["expense","withdrawal"].includes(row.movement_type),files=evidenceFor(row.id);return `<tr><td>${formatDate(row.movement_date)}</td><td><span class="tr-badge ${negative?"bad":"good"}">${labels[row.movement_type]||row.movement_type}</span></td><td><strong>${esc(row.category)}</strong><small>${esc(row.description||row.reference||"Sin detalle")}${row.updated_at?` · Modificado ${formatDateTime(row.updated_at)}`:""}</small></td><td>${esc(contract?.contract_number||"—")}</td><td>${esc(row.payment_method||"—")}</td><td><strong>${esc(row.registered_by_name||"Sistema")}</strong><small>${esc(row.registered_by_email||"")}</small></td><td>${files.length?`<button class="tr-evidence-count" type="button" data-tr-evidence="${esc(row.id)}">${files.length} imagen${files.length===1?"":"es"}</button>`:`<small>Sin evidencia</small>`}</td><td class="tr-amount"><strong>${negative?"−":"+"}${formatMoney(row.amount,row.currency)}</strong></td><td><div class="tr-row-actions">${capability("edit_movements")?`<button type="button" data-tr-edit-movement="${esc(row.id)}">Editar</button>`:""}</div></td></tr>`;}).join(""):`<tr><td colspan="9"><div class="tr-empty">Registra un aporte, ingreso o gasto para iniciar la bóveda.</div></td></tr>`;
    renderPagination("movements",store.movements.length,"trMovementsPagination");
  }

  function auditDetail(row){const data=row.after_data||row.before_data||{};if(row.entity_type==="movement")return [data.category,data.reference].filter(Boolean).join(" · ")||"Movimiento financiero";if(row.entity_type==="contract")return [data.contract_number,data.client_name].filter(Boolean).join(" · ")||"Contrato";return [data.description,data.due_date].filter(Boolean).join(" · ")||"Cuota";}
  function renderAudit(){const host=byId("trAuditBody");if(!host)return;const action={created:"Creado",updated:"Modificado",deleted:"Eliminado"},entity={contract:"Contrato",installment:"Cuota",movement:"Movimiento"},page=pageRows(store.audit,"audit");host.innerHTML=store.audit.length?page.rows.map((row)=>`<tr><td>${formatDateTime(row.created_at)}</td><td><span class="tr-badge ${row.action==="deleted"?"bad":row.action==="updated"?"warn":"good"}">${esc(action[row.action]||row.action)}</span></td><td>${esc(entity[row.entity_type]||row.entity_type)}</td><td><code>${esc(String(row.entity_id||"").slice(0,8))}</code></td><td><strong>${esc(row.actor_name||"Sistema")}</strong><small>${esc(row.actor_email||"")}</small></td><td>${esc(auditDetail(row))}</td></tr>`).join(""):`<tr><td colspan="6"><div class="tr-empty">La auditoría comenzará con la próxima operación financiera.</div></td></tr>`;renderPagination("audit",store.audit.length,"trAuditPagination");}

  function renderDetail() {
    const row=store.contracts.find((item)=>item.id===store.selectedId); if(!row)return;
    const paid=contractIncome(row.id),balance=Math.max(0,amount(row.total_amount)-paid),status=contractStatus(row),events=store.events.filter((event)=>event.contract_id===row.id),labels={created:"Creado",updated:"Actualizado",status_changed:"Estado modificado"};
    byId("trDetailSubtitle").textContent=`${row.contract_number} · ${row.client_name}`;
    byId("trDetailBody").innerHTML=`<div class="tr-detail-summary"><article><span>Total</span><strong>${formatMoney(row.total_amount,row.currency)}</strong></article><article><span>Cobrado</span><strong>${formatMoney(paid,row.currency)}</strong></article><article><span>Saldo</span><strong>${formatMoney(balance,row.currency)}</strong></article><article><span>Estado</span><strong><i class="tr-badge ${status[1]}">${status[0]}</i></strong></article></div>
      <div class="tr-detail-actions">${capability("record_payment")&&row.status!=="cancelled"?`<button class="tr-primary" type="button" data-tr-pay="${esc(row.id)}">Registrar cobro</button>`:""}${capability("edit")&&row.status!=="cancelled"?`<button type="button" data-tr-edit="${esc(row.id)}">Editar datos</button>`:""}${capability("export")?`<button type="button" data-tr-print="${esc(row.id)}">Imprimir contrato</button>`:""}</div>
      <div class="tr-detail-grid"><section><h4>Cuotas y cobranza</h4><div class="tr-installments">${installmentsFor(row.id).map((item)=>{const itemPaid=installmentPaid(item.id),pending=Math.max(0,amount(item.amount)-itemPaid),late=item.due_date<todayIso()&&pending>.009,days=late?Math.max(1,Math.floor((Date.now()-parseDate(item.due_date).getTime())/86400000)):0;return `<article class="${late?"late":""}"><div><strong>Cuota ${item.installment_number}: ${esc(item.description)}</strong><small>${late?`Vencida hace ${days} día${days===1?"":"s"}`:`Vence ${formatDate(item.due_date)}`}</small></div><div><strong>${formatMoney(pending,row.currency)}</strong><small>${pending?"pendiente":"pagada"}</small></div></article>`;}).join("")||"<div class='tr-empty'>Sin cuotas.</div>"}</div></section><section><h4>Historial del contrato</h4><div class="tr-events">${events.map((event)=>`<article><i></i><div><strong>${esc(labels[event.event_type]||event.event_type)}</strong><small>${formatDateTime(event.created_at)} · ${esc(event.actor_name||event.actor_email||"Sistema")}${event.previous_status?` · ${esc(event.previous_status)} → ${esc(event.new_status)}`:""}</small><p>${esc(event.note||"Sin observación")}</p></div></article>`).join("")||"<div class='tr-empty'>Sin cambios registrados.</div>"}</div></section></div>
      ${capability("edit")&&row.status!=="cancelled"?`<form class="tr-status-form" id="trStatusForm"><label><span>Cambiar estado contractual</span><select id="trNewStatus"><option value="active" ${row.status==="active"?"selected":""}>Activo</option><option value="draft" ${row.status==="draft"?"selected":""}>Borrador</option><option value="completed" ${row.status==="completed"?"selected":""}>Completado</option>${capability("cancel")?`<option value="cancelled">Anulado</option>`:""}</select></label><label class="tr-grow"><span>Motivo u observación</span><input id="trStatusReason" maxlength="240" placeholder="Obligatorio para anular"></label><button type="submit">Actualizar estado</button></form>`:""}`;
  }

  function renderAll(){renderKpis();renderOverdueAlerts();renderChart();renderContracts();renderMovements();renderAudit();fillContractOptions();syncControls();if(store.selectedId)renderDetail();}

  function syncControls(){byId("trNewContract").hidden=!capability("create");byId("trNewMovement").hidden=!capability("record_payment");byId("trExportContracts").hidden=!capability("export");byId("trAuditTab").hidden=!capability("audit");}

  async function load(){const status=byId("trStatus");status.textContent="Cargando datos financieros…";const result=await service()?.load();if(!result?.ok){status.textContent=result?.error||"No disponible";return;}const data=result.data||{};store.contracts=data.contracts||[];store.installments=data.installments||[];store.movements=data.movements||[];store.events=data.events||[];store.audit=data.audit||[];store.evidence=data.evidence||[];store.overdueAlerts=data.overdue_alerts||[];store.capabilities=data.capabilities||{};store.loaded=true;status.textContent=`Actualizado ${new Date().toLocaleTimeString("es-PE",{hour:"2-digit",minute:"2-digit"})}`;renderAll();}

  function fillContractOptions(){const select=byId("trMovementContract"),selected=select?.value||"";if(!select)return;select.innerHTML=`<option value="">Sin contrato</option>`+store.contracts.filter((row)=>row.status!=="cancelled").map((row)=>`<option value="${esc(row.id)}">${esc(row.contract_number)} · ${esc(row.client_name)}</option>`).join("");select.value=selected;fillInstallments();}
  function fillInstallments(){const contractId=byId("trMovementContract")?.value,select=byId("trMovementInstallment");if(!select)return;select.innerHTML=`<option value="">Sin cuota específica</option>`+store.installments.filter((row)=>row.contract_id===contractId&&amount(row.amount)-installmentPaid(row.id)>.009).map((row)=>`<option value="${esc(row.id)}">Cuota ${row.installment_number} · ${formatDate(row.due_date)} · ${formatMoney(Math.max(0,amount(row.amount)-installmentPaid(row.id)))}</option>`).join("");}

  async function lookup(){const type=byId("trDocumentType").value.toLowerCase(),documentNumber=byId("trDocument").value.replace(/\D/g,""),note=byId("trApiNote");if(type==="ce"){note.textContent="La consulta automática sólo está disponible para DNI y RUC.";return;}note.textContent="Consultando…";byId("trLookup").disabled=true;const result=await service()?.lookupDocument(type,documentNumber);byId("trLookup").disabled=false;if(!result?.ok){note.textContent=`${result?.error||"No se encontró información."} Puedes continuar manualmente.`;return;}byId("trClientName").value=result.data.name||"";byId("trClientAddress").value=result.data.address||"";note.textContent="Datos encontrados. Verifica la información antes de guardar.";}

  function contractPayload(){return {client_document_type:byId("trDocumentType").value,client_document:byId("trDocument").value.replace(/\D/g,""),client_name:byId("trClientName").value.trim(),client_address:byId("trClientAddress").value.trim(),client_phone:byId("trClientPhone").value.trim(),client_email:byId("trClientEmail").value.trim(),service_date:byId("trServiceDate").value,service_name:byId("trServiceName").value.trim(),service_description:byId("trServiceDescription").value.trim(),deliverables:byId("trDeliverables").value.split(/\r?\n/).map((line)=>line.trim()).filter(Boolean),total_amount:amount(byId("trTotal").value),first_payment_percent:amount(byId("trFirstPercent").value),delivery_days:Number(byId("trDeliveryDays").value),currency:byId("trCurrency").value,notes:byId("trContractNotes").value.trim(),change_note:byId("trChangeNote").value.trim()};}

  async function saveContract(event){event.preventDefault();const submit=event.submitter,id=byId("trContractId").value;if(submit)submit.disabled=true;const result=id?await service()?.updateContract(id,contractPayload()):await service()?.createContract(contractPayload());if(submit)submit.disabled=false;if(!result?.ok){byId("trApiNote").textContent=result?.error||"No se pudo guardar el contrato.";return;}byId("trContractDialog").close();resetContractForm();await load();switchTab("contracts");}
  function selectedEvidenceFiles(){return Array.from(byId("trMovementEvidence")?.files||[]);}
  function validateEvidenceFiles(files){const allowed=["image/jpeg","image/png","image/webp"];if(files.length>5)return "Puedes adjuntar como máximo 5 imágenes por operación.";const invalid=files.find((file)=>!allowed.includes(file.type)||!file.size||file.size>10*1024*1024);if(invalid)return `Revisa ${invalid.name}: solo JPG, PNG o WebP de hasta 10 MB.`;return "";}
  function showSelectedEvidence(){const files=selectedEvidenceFiles();byId("trMovementEvidenceList").textContent=files.length?files.map((file)=>file.name).join(" · "):"";}
  async function saveMovement(event){event.preventDefault();const submit=event.submitter,id=byId("trMovementId").value,files=selectedEvidenceFiles(),fileError=validateEvidenceFiles(files);if(fileError){alert(fileError);return;}if(submit)submit.disabled=true;const payload={movement_type:byId("trMovementType").value,movement_date:byId("trMovementDate").value,contract_id:byId("trMovementContract").value||null,installment_id:byId("trMovementInstallment").value||null,category:byId("trMovementCategory").value.trim(),amount:amount(byId("trMovementAmount").value),payment_method:byId("trPaymentMethod").value,reference:byId("trMovementReference").value.trim(),description:byId("trMovementDescription").value.trim(),currency:"PEN"};const result=id?await service()?.updateMovement(id,payload,byId("trMovementReason").value.trim()):await service()?.addMovement(payload);if(!result?.ok){if(submit)submit.disabled=false;alert(result?.error||"No se pudo guardar el movimiento.");return;}const movementId=id||result.data?.movement?.id;for(const file of files){const uploaded=await service()?.uploadMovementEvidence(movementId,file);if(!uploaded?.ok){if(submit)submit.disabled=false;alert(`El movimiento fue guardado, pero no se pudo subir ${file.name}: ${uploaded?.error||"error desconocido"}`);await load();return;}}if(submit)submit.disabled=false;byId("trMovementDialog").close();resetMovementForm();await load();switchTab("movements");}

  function resetContractForm(){byId("trContractForm").reset();byId("trContractId").value="";byId("trFirstPercent").value="50";byId("trDeliveryDays").value="7";byId("trContractDialogTitle").textContent="Registrar contrato";byId("trDocument").readOnly=false;byId("trDocumentType").disabled=false;byId("trCurrency").disabled=false;byId("trLookup").hidden=false;byId("trFirstPercentLabel").hidden=false;byId("trChangeNoteLabel").hidden=true;}
  function resetMovementForm(){byId("trMovementForm").reset();byId("trMovementId").value="";byId("trMovementDate").value=todayIso();byId("trMovementCategory").value="Cobranza";byId("trMovementDialogTitle").textContent="Registrar movimiento";byId("trMovementSubmit").textContent="Registrar movimiento";byId("trMovementContract").disabled=false;byId("trMovementInstallment").disabled=false;byId("trMovementReasonLabel").hidden=true;byId("trMovementReason").required=false;byId("trMovementEvidenceList").textContent="";fillContractOptions();}
  function editMovement(id){const row=store.movements.find((item)=>item.id===id);if(!row)return;resetMovementForm();byId("trMovementId").value=row.id;byId("trMovementDialogTitle").textContent="Editar movimiento";byId("trMovementSubmit").textContent="Guardar corrección";byId("trMovementType").value=row.movement_type;byId("trMovementDate").value=String(row.movement_date||"").slice(0,10);byId("trMovementContract").value=row.contract_id||"";fillInstallments();if(row.installment_id&&!Array.from(byId("trMovementInstallment").options).some((option)=>option.value===row.installment_id)){const installment=store.installments.find((item)=>item.id===row.installment_id);byId("trMovementInstallment").add(new Option(`Cuota ${installment?.installment_number||"relacionada"}`,row.installment_id));}byId("trMovementInstallment").value=row.installment_id||"";byId("trMovementCategory").value=row.category||"";byId("trMovementAmount").value=row.amount;byId("trPaymentMethod").value=row.payment_method||"transfer";byId("trMovementReference").value=row.reference||"";byId("trMovementDescription").value=row.description||"";byId("trMovementContract").disabled=true;byId("trMovementInstallment").disabled=true;byId("trMovementReasonLabel").hidden=false;byId("trMovementReason").required=true;byId("trMovementDialog").showModal();}
  function showEvidence(id){const files=evidenceFor(id);byId("trEvidenceBody").innerHTML=files.length?files.map((file)=>`<button class="tr-evidence-file" type="button" data-tr-open-evidence="${esc(file.storage_path)}"><span>${esc(file.file_name)}</span><small>${esc(file.uploaded_by_name||"Sistema")} · ${formatDateTime(file.created_at)} · ${(Number(file.file_size)/1048576).toFixed(2)} MB</small></button>`).join(""):`<div class="tr-empty">Este movimiento todavía no tiene evidencias.</div>`;byId("trEvidenceDialog").showModal();}
  async function openEvidence(path){const result=await service()?.createEvidenceUrl(path);if(!result?.ok||!result.data){alert(result?.error||"No se pudo abrir la evidencia.");return;}global.open(result.data,"_blank","noopener,noreferrer");}
  function editContract(id){const row=store.contracts.find((item)=>item.id===id);if(!row)return;resetContractForm();byId("trContractId").value=row.id;byId("trContractDialogTitle").textContent=`Editar ${row.contract_number}`;byId("trDocumentType").value=row.client_document_type;byId("trDocument").value=row.client_document;byId("trClientName").value=row.client_name;byId("trClientAddress").value=row.client_address||"";byId("trClientPhone").value=row.client_phone||"";byId("trClientEmail").value=row.client_email||"";byId("trServiceDate").value=String(row.service_date||"").slice(0,10);byId("trServiceName").value=row.service_name;byId("trServiceDescription").value=row.service_description||"";byId("trDeliverables").value=(row.deliverables||[]).join("\n");byId("trTotal").value=row.total_amount;byId("trDeliveryDays").value=row.delivery_days;byId("trCurrency").value=row.currency;byId("trContractNotes").value=row.notes||"";byId("trDocument").readOnly=true;byId("trDocumentType").disabled=true;byId("trCurrency").disabled=true;byId("trLookup").hidden=true;byId("trFirstPercentLabel").hidden=true;byId("trChangeNoteLabel").hidden=false;byId("trContractDialog").showModal();}

  async function setStatus(event){event.preventDefault();const result=await service()?.setContractStatus(store.selectedId,byId("trNewStatus").value,byId("trStatusReason").value.trim());if(!result?.ok){alert(result?.error||"No se pudo actualizar el estado.");return;}await load();renderDetail();}
  function openPayment(id){byId("trDetailDialog").close();openDialog("trMovementDialog");byId("trMovementType").value="income";byId("trMovementCategory").value="Cobranza";byId("trMovementContract").value=id;fillInstallments();const first=byId("trMovementInstallment").options[1];if(first){byId("trMovementInstallment").value=first.value;const installment=store.installments.find((row)=>row.id===first.value);byId("trMovementAmount").value=Math.max(0,amount(installment?.amount)-installmentPaid(installment?.id));}}

  function printContract(id){const row=store.contracts.find((item)=>item.id===id);if(!row)return;const deliverables=Array.isArray(row.deliverables)?row.deliverables:[],first=amount(row.total_amount)*amount(row.payment_terms?.first_payment_percent||50)/100;byId("treasury-print").innerHTML=`<div class="tr-print-head"><div class="tr-print-logo">ONE <span style="font-size:.55em;letter-spacing:-.04em">Studios</span></div><strong>${formatDate(row.created_at)}</strong></div><h1>CONTRATO DE PRESTACIÓN DE SERVICIOS</h1><p>Conste por el presente documento el Contrato de Prestación de Servicios que celebran, por una parte, ONE STUDIOS, en adelante “EL PRESTADOR”, y por la otra: <strong>${esc(row.client_name)}</strong>, ${esc(row.client_document_type)}: <strong>${esc(row.client_document)}</strong>, en adelante “LA CONTRATANTE”.</p><h2>PRIMERA: OBJETO DEL CONTRATO</h2><p>ONE STUDIOS se compromete a brindar el servicio profesional de <strong>${esc(row.service_name)}</strong>. ${esc(row.service_description)}</p><h2>SEGUNDA: DETALLE DEL SERVICIO CONTRATADO</h2>${deliverables.length?`<ul>${deliverables.map((item)=>`<li>${esc(item)}</li>`).join("")}</ul>`:"<p>Según la descripción y coordinaciones registradas entre las partes.</p>"}<h2>TERCERA: PRECIO Y FORMA DE PAGO</h2><p>El costo total asciende a <strong>${formatMoney(row.total_amount,row.currency)}</strong>. Primer abono: ${formatMoney(first,row.currency)}. Saldo: ${formatMoney(amount(row.total_amount)-first,row.currency)}. La reserva queda confirmada con el primer abono.</p><h2>CUARTA: ENTREGA DEL MATERIAL</h2><p>ONE STUDIOS entregará el material contratado, debidamente finalizado, en un plazo máximo de ${esc(row.delivery_days)} días calendario contados desde la fecha del servicio.</p><div class="tr-print-signatures"><div class="tr-signature"><strong>Miguel Angel Jaco Araujo</strong><br>Representante ONE STUDIOS</div><div class="tr-signature"><strong>${esc(row.client_name)}</strong><br>Contratante</div></div><div class="tr-print-footer">Pasaje Guido 726 · ventas@onestudioslabs.com · 974 606 316 · ${esc(row.contract_number)}</div>`;global.print();}

  function exportCsv(){const rows=[["Contrato","Cliente","Documento","Servicio","Fecha","Total","Cobrado","Saldo","Estado"],...filteredContracts().map((row)=>[row.contract_number,row.client_name,`${row.client_document_type} ${row.client_document}`,row.service_name,row.service_date,row.total_amount,contractIncome(row.id),Math.max(0,amount(row.total_amount)-contractIncome(row.id)),contractStatus(row)[0]])];const quote=(value)=>`"${String(value??"").replaceAll('"','""')}"`,blob=new Blob([rows.map((row)=>row.map(quote).join(",")).join("\n")],{type:"text/csv;charset=utf-8"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`contratos_${todayIso()}.csv`;link.click();URL.revokeObjectURL(link.href);}
  function switchTab(tab){root.querySelectorAll("[data-tr-tab]").forEach((button)=>button.classList.toggle("active",button.dataset.trTab===tab));root.querySelectorAll("[data-tr-panel]").forEach((panel)=>panel.classList.toggle("active",panel.dataset.trPanel===tab));}
  function openDialog(id){const dialog=byId(id);if(id==="trContractDialog"){resetContractForm();byId("trServiceDate").value=todayIso();}if(id==="trMovementDialog")resetMovementForm();dialog.showModal();}
  function openDetail(id){store.selectedId=id;renderDetail();byId("trDetailDialog").showModal();}
  function syncAccess(){const allowed=global.OneStudios?.permissions?.isAllowed?.("treasury.view")??(typeof hasVisualPermission==="function"?hasVisualPermission("treasury","view"):false);const topButton=document.querySelector('[data-v472-menu="finanzas"]');if(topButton)topButton.hidden=!allowed;}

  function bind(){byId("trRefresh").addEventListener("click",load);byId("trNewContract").addEventListener("click",()=>openDialog("trContractDialog"));byId("trNewMovement").addEventListener("click",()=>openDialog("trMovementDialog"));byId("trLookup").addEventListener("click",lookup);byId("trContractForm").addEventListener("submit",saveContract);byId("trMovementForm").addEventListener("submit",saveMovement);byId("trMovementContract").addEventListener("change",fillInstallments);byId("trMovementEvidence").addEventListener("change",showSelectedEvidence);byId("trContractSearch").addEventListener("input",(event)=>{store.filters.query=event.target.value;renderContracts();});byId("trContractStatus").addEventListener("change",(event)=>{store.filters.status=event.target.value;renderContracts();});byId("trExportContracts").addEventListener("click",exportCsv);
    root.addEventListener("submit",(event)=>{if(event.target.id==="trStatusForm")setStatus(event);});
    root.addEventListener("click",(event)=>{const tab=event.target.closest("[data-tr-tab]");if(tab)switchTab(tab.dataset.trTab);const close=event.target.closest("[data-tr-close]");if(close)byId(close.dataset.trClose).close();const print=event.target.closest("[data-tr-print]");if(print)printContract(print.dataset.trPrint);const detail=event.target.closest("[data-tr-detail]");if(detail)openDetail(detail.dataset.trDetail);const edit=event.target.closest("[data-tr-edit]");if(edit){byId("trDetailDialog").close();editContract(edit.dataset.trEdit);}const editMovementButton=event.target.closest("[data-tr-edit-movement]");if(editMovementButton)editMovement(editMovementButton.dataset.trEditMovement);const evidence=event.target.closest("[data-tr-evidence]");if(evidence)showEvidence(evidence.dataset.trEvidence);const evidenceFile=event.target.closest("[data-tr-open-evidence]");if(evidenceFile)openEvidence(evidenceFile.dataset.trOpenEvidence);const pageButton=event.target.closest("[data-tr-page-target]");if(pageButton&&!pageButton.disabled){const key=pageButton.dataset.trPageTarget;store.pagination[key]+=Number(pageButton.dataset.trPageDelta||0);if(key==="movements")renderMovements();if(key==="audit")renderAudit();}const pay=event.target.closest("[data-tr-pay]");if(pay)openPayment(pay.dataset.trPay);});
    document.querySelector('[data-section="treasury"]')?.addEventListener("click",()=>{global.setTimeout(()=>{if(byId("pageTitle"))byId("pageTitle").textContent="Tesorería y contratos";},0);if(!store.loaded)load();});global.addEventListener("inbestiga:session-ready",()=>{syncAccess();load();});global.addEventListener("inbestiga:permissions-ready",syncAccess);}

  shell();bind();renderAll();global.setTimeout(syncAccess,0);
})(window);
